#include "Config.hpp"
#include <fstream>
#include <cstdio>
#include <cstring>
#include <sys/stat.h>

Config::Config() 
    : mLoggingEnabled(false)
    , mVerboseLogging(false)
    , mLanguage("en-us")  // 默认英文
    , mDownloadPath("fs:/vol/external01/themes/")
    , mAutoInstall(true)
    , mBgmEnabled(true)   // 默认开启背景音乐
    , mBgmUrl("https://raw.githubusercontent.com/xziip/utheme/main/data/BGM.mp3")  // 默认BGM下载地址
    , mConfigPath("fs:/vol/external01/wiiu/utheme.cfg") {
    Load();
}

Config::~Config() {
    Save();
}

Config& Config::GetInstance() {
    static Config instance;
    return instance;
}

void Config::SetLoggingEnabled(bool enabled) {
    if (mLoggingEnabled != enabled) {
        mLoggingEnabled = enabled;
        Save();
    }
}

void Config::SetVerboseLogging(bool verbose) {
    if (mVerboseLogging != verbose) {
        mVerboseLogging = verbose;
        Save();
    }
}

void Config::SetLanguage(const std::string& lang) {
    if (mLanguage != lang) {
        mLanguage = lang;
        Save();
    }
}

void Config::SetDownloadPath(const std::string& path) {
    if (mDownloadPath != path) {
        mDownloadPath = path;
        Save();
    }
}

void Config::SetAutoInstallEnabled(bool enabled) {
    if (mAutoInstall != enabled) {
        mAutoInstall = enabled;
        Save();
    }
}

void Config::SetBgmEnabled(bool enabled) {
    if (mBgmEnabled != enabled) {
        mBgmEnabled = enabled;
        Save();
    }
}

void Config::SetBgmUrl(const std::string& url) {
    if (mBgmUrl != url) {
        mBgmUrl = url;
        Save();
    }
}

bool Config::Load() {
    FILE* file = fopen(mConfigPath.c_str(), "r");
    if (!file) {
        // 配置文件不存在,使用默认值
        return false;
    }
    
    char line[512];
    while (fgets(line, sizeof(line), file)) {
        // 移除换行符
        size_t len = strlen(line);
        if (len > 0 && line[len-1] == '\n') {
            line[len-1] = '\0';
        }
        
        if (strncmp(line, "logging=", 8) == 0) {
            mLoggingEnabled = (line[8] == '1');
        } else if (strncmp(line, "verbose=", 8) == 0) {
            mVerboseLogging = (line[8] == '1');
        } else if (strncmp(line, "language=", 9) == 0) {
            mLanguage = &line[9];
        } else if (strncmp(line, "downloadpath=", 13) == 0) {
            mDownloadPath = &line[13];
        } else if (strncmp(line, "autoinstall=", 12) == 0) {
            mAutoInstall = (line[12] == '1');
        } else if (strncmp(line, "bgm=", 4) == 0) {
            mBgmEnabled = (line[4] == '1');
        } else if (strncmp(line, "bgmurl=", 7) == 0) {
            mBgmUrl = &line[7];
        }
    }
    
    fclose(file);
    return true;
}

bool Config::Save() {
    // 确保目录存在
    const char* dirPath = "fs:/vol/external01/wiiu";
    struct stat st;
    if (stat(dirPath, &st) != 0) {
        mkdir(dirPath, 0777);
    }
    
    FILE* file = fopen(mConfigPath.c_str(), "w");
    if (!file) {
        return false;
    }
    
    fprintf(file, "# UTheme Configuration File\n");
    fprintf(file, "# This file is automatically generated\n\n");
    
    fprintf(file, "# Logging settings\n");
    fprintf(file, "logging=%d\n", mLoggingEnabled ? 1 : 0);
    fprintf(file, "verbose=%d\n", mVerboseLogging ? 1 : 0);
    fprintf(file, "\n");
    
    fprintf(file, "# Language (zh-cn, en-us, ja-jp)\n");
    fprintf(file, "language=%s\n", mLanguage.c_str());
    fprintf(file, "\n");
    
    fprintf(file, "# Download path\n");
    fprintf(file, "downloadpath=%s\n", mDownloadPath.c_str());
    fprintf(file, "\n");
    
    fprintf(file, "# Auto install after download\n");
    fprintf(file, "autoinstall=%d\n", mAutoInstall ? 1 : 0);
    fprintf(file, "\n");
    
    fprintf(file, "# Background music\n");
    fprintf(file, "bgm=%d\n", mBgmEnabled ? 1 : 0);
    fprintf(file, "bgmurl=%s\n", mBgmUrl.c_str());
    
    fclose(file);
    return true;
}
